spring.application.name=usage-service
server.port=8083

###############################################################################
# Kafka Consumer Infrastructure Configuration
###############################################################################
# Target the external KRaft port exposed on your local host machine
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=usage-service

# Fixed property keys configuration strings
spring.kafka.consumer.properties.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.value.deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Explicit trusted packages declaration (Required for safety when using JsonDeserializer)
spring.kafka.consumer.properties.spring.json.trusted.packages=com.kushal.*
spring.kafka.consumer.properties.spring.json.type.mapping=energyUsageEvent:com.kushal.kafka.event.EnergyUsageEvent

#Kafka - producer
# Kafka - Producer Configuration Properties
spring.kafka.template.default-topic=energy-alerts
spring.kafka.producer.properties.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.properties.value.serializer=org.springframework.kafka.support.serializer.JsonSerializer

###############################################################################
# InfluxDB Time-Series Configuration
###############################################################################
influx.url=http://localhost:8072
influx.token=my-token
influx.org=kushal
influx.bucket=usage-bucket

device.service.url=http://localhost:8081/api/v1/device
user.service.url=http://localhost:8080/api/v1/user